### ISSUE TITLE
not working for one account

### ISSUE THREAD

**Issue by rejuanad99** [canaria3406/hoyolab-auto-sign#11]
![Screenshot_2023-05-19-19-37-54-71_1149b56b894fd37d9a6fe46f85aae740](https://github.com/canaria3406/hoyolab-auto-sign/assets/49226370/4dc90b3e-79ef-4d0f-9105-66bdfaa15272)

![Screenshot_2023-05-19-19-38-00-96_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/canaria3406/hoyolab-auto-sign/assets/49226370/64166b7c-8a6c-4b88-8b8a-e199f61e8f7e)
I've tried everything i can think of yet one of the account isn't working, the other one work. But the second one doesn't work.

**Comment by canaria3406** [comment]
Do you mean that one of the accounts is unable to execute, but the other two accounts can execute?

You can try logging into `www.hoyolab.com/circles/` on PC with that account and manually attempt the check-in process.
If the check-in is successful, there might not be any issue. Please copy the token and try again.
If not, please check the status of your account.

**Comment by no-one-1-kol** [comment]
> Do you mean that one of the accounts is unable to execute, but the other two accounts can execute?
> 
> You can try logging into `www.hoyolab.com/circles/` on PC with that account and manually attempt the check-in process. If the check-in is successful, there might not be any issue. Please copy the token and try again. If not, please check the status of your account.

I'm also getting this problem on 2 of the 5 accounts I have tested. I have checked the token multiple times, so I am fairly sure it is not because of that. One anomaly I have found is that when logging into those 2 accounts, a google security notification pops up, as well as a required CAPTCHA when actually claiming the rewards on the genshin check-in page, so I assume that might be stopping the script?

![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/111351791/c4b800b1-1720-4ca2-b8e9-57ac9f47ffa9)

**Comment by Terra00** [comment]
I've been trying to use this script and it works with Star Rail but not Genshin, it seems to ask for the captcha every time the script runs. Most likely it's Hoyoverse that has raised some sort of protection to avoid this type of script, but strange that they only did it for Genshin and nothing else.

**Comment by Dekerz12** [comment]
Same thing happened to me, ig some accounts need captcha verification (on genshin) before claiming daily check-in.

**Comment by canaria3406** [comment]
Are all the accounts experiencing this issue new accounts?
I suspect that for new accounts, there might be captcha issues during initial check-in, which require manual completion of the check-in process few days.

**Comment by xitrumIT** [comment]
I also get the same error, I have 4 accounts and 1 out of 4 that accounts need to capcha to reward on website, but telegram notification is always successful get reward

**Comment by no-one-1-kol** [comment]
> Are all the accounts experiencing this issue new accounts? I suspect that for new accounts, there might be captcha issues during initial check-in, which require manual completion of the check-in process few days.

The accounts I've tried are a couple of years old, and the requirement for the CAPTCHA is unknown so far. As a further note, it seems to only randomly have a CAPTCHA on the 6th account. 

I'm not too sure how rn but you could try having an error message instead of an OK when the script runs into a CAPTCHA for a specific check-in, would be less misleading.

**Comment by xitrumIT** [comment]
<img width="888" alt="image" src="https://github.com/canaria3406/hoyolab-auto-sign/assets/7894299/0c7b0ba5-eda1-4887-9c13-edd103a99661">
i think we have same issue, but i don't know how to add 'User-Agent' to your project

**Comment by AgentEggs35** [comment]
I'm having the same issue. I want to add that I definitely have a required CAPTCHA every single day for Genshin only and the bot still works for Star Rail.

One thing I've noticed is that the CAPTCHA thing also broke the Check-In button in the Hoyolab app; even that claims to be completed but only physically going to the website and filling out the CAPTCHA actually gives me the check-in.

**Comment by Chillrend** [comment]
> > Are all the accounts experiencing this issue new accounts? I suspect that for new accounts, there might be captcha issues during initial check-in, which require manual completion of the check-in process few days.
> 
> The accounts I've tried are a couple of years old, and the requirement for the CAPTCHA is unknown so far. As a further note, it seems to only randomly have a CAPTCHA on the 6th account.
> 
> I'm not too sure how rn but you could try having an error message instead of an OK when the script runs into a CAPTCHA for a specific check-in, would be less misleading.

The problem is the endpoint is reporting 'OK' even if the check-in process failed because of captcha. So, we have no idea to determine if it failed.

**Comment by canaria3406** [comment]
merge to issue #16
