### ISSUE TITLE
Doubt regarding setting up environmental variables in google script

### ISSUE THREAD

**Issue by KAZUYA892** [canaria3406/hoyolab-auto-sign#14]
Hello,
First of all I want to convey my gratitude to @canaria3406 for creating this script. 

I have a question. I heard that cookies data shouldn't be shared with anyone. How we can set up environmental variables in google script? Or there is nothing to worry about as my project in google script is private and no one can view my secret values. 

Waiting for your response and thankyou.

**Comment by Dekerz12** [comment]
> Hello, First of all I want to convey my gratitude to @canaria3406 for creating this script.
> 
> I have a question. I heard that cookies data shouldn't be shared with anyone. How we can set up environmental variables in google script? Or there is nothing to worry about as my project in google script is private and no one can view my secret values.
> 
> Waiting for your response and thankyou.

First you need to stringify the array of objects and log it to the console, then copy paste it to the script properties on settings inside your google app script, to access the variable just see the documentation about it, u need to parse the JSON file after you've accessed the variable.

 
![image2](https://github.com/canaria3406/hoyolab-auto-sign/assets/124056161/4f1f0ba8-5174-45ea-8a64-a3def71c5062)
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/124056161/65b4c8d9-1698-4e0d-87b1-cca96fafa1c2)
![image1](https://github.com/canaria3406/hoyolab-auto-sign/assets/124056161/baa25823-735a-4094-b556-91a7862ba2c4)

**Comment by KAZUYA892** [comment]
Thnx
