### ISSUE TITLE
Cookie token code seems to have stopped working

### ISSUE THREAD

**Issue by cd36th** [canaria3406/hoyolab-auto-sign#18]
Only returns "ltoken=undefined; ltuid=undefined;"

**Comment by jason21415** [comment]
i test is works.
maybe you should try to log in again.

[hoyolab
](https://act.hoyolab.com/app/community-game-records-sea/index.html?bbs_auth_required=true&bbs_presentation_style=fullscreen&gid=6&utm_campaign=battlechronicle&utm_id=6&utm_medium=tools&utm_source=hoyolab&v=101&bbs_theme=light&bbs_theme_device=1#/hsr)

token
f12>console>Paste>get token

```
function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}
let token = 'ltoken=' + getCookie('ltoken') + '; ltuid=' + getCookie('ltuid') + ';';
let ask = confirm(token + '\n\nPress enter, then paste the token into your Google Apps Script Project');
if (ask == true) {
  copy(token);
  msg = token;
} else {
  msg = 'Cancel';
}
```

**Comment by jason21415** [comment]
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/57126581/ec973960-26a7-49f8-8ad6-5c55949e786e)

**Comment by cd36th** [comment]
ok yeah relogging worked thank you, didnt try that because genshin wizard which also uses tokens has disabled token stuff temporarily to fix things
