### ISSUE TITLE
how to avoid CAPTCHA?

### ISSUE THREAD

**Issue by c436zhan** [canaria3406/hoyolab-auto-sign#22]
Only gets CAPTCHA for genshin. Star rails is fine. How to avoid it?

**Comment by nautilust** [comment]
I got same issues, it's not working now
![Screenshot_20230819-221353](https://github.com/canaria3406/hoyolab-auto-sign/assets/88370785/0b4a7b9c-daea-4665-81ef-b1f70917d318)

**Comment by alwaysmiddle** [comment]
I think if you do the captcha for few days, hoyolab will flag you not needing captcha. But if you do not log into hoyolab for while, it will flag you again.

**Comment by nautilust** [comment]
> I think if you do the captcha for few days manually, hoyolab will unflag you for bot. But if you do not log into hoyolab for while, it will flag you again, requiring CAPTCHA.

Maybe it could, but it would take away the meaning of auto check-in this script

**Comment by alwaysmiddle** [comment]
> > I think if you do the captcha for few days manually, hoyolab will unflag you for bot. But if you do not log into hoyolab for while, it will flag you again, requiring CAPTCHA.
> 
> Maybe it could, but it would take away the meaning of auto check-in this script

You can check the [issue discussed here in the other thread](https://github.com/canaria3406/hoyolab-auto-sign/issues/16), you will notice basically Hoyoverse blocked all bots, so techinically this is best compromise you have at the moment.
