### ISSUE TITLE
Changed the password of Hoyolab account and the auto-sign stopped

### ISSUE THREAD

**Issue by vomenh1804** [canaria3406/hoyolab-auto-sign#26]
So I changed my account password, then the old auto-sign keep inform me to log in
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/145992865/490143d6-b24d-4431-b9f7-e751125de61e)
I tried to get new token but it say error
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/145992865/6eace332-31f9-49d8-a7a9-2e7c6a904cf6)
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/145992865/5c56d2bf-7107-46da-a4a8-85f7393562a4)

**Comment by canaria3406** [comment]
Please try the code below.  
If it works, please tell me, thanks!

```javascript
function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}
let token = 'Error';
if (document.cookie.includes('ltoken=')) {
  token = `ltoken=${getCookie('ltoken')}; ltuid=${getCookie('ltuid')};`;
} else if (document.cookie.includes('ltoken_v2=')) {
  token = `account_mid_v2=${getCookie('account_mid_v2')}; account_id_v2=${getCookie('account_id_v2')}; ltoken_v2=${getCookie('ltoken_v2')}; ltmid_v2=${getCookie('ltmid_v2')}; ltuid_v2=${getCookie('ltuid_v2')};`;
} else { 
  token = document.cookie;
}
let ask = confirm(token + '\n\nPress enter, then paste the token into your Google Apps Script Project');
if (ask) {
  copy(token);
  msg = token;
} else {
  msg = 'Cancel';
}
```

**Comment by vomenh1804** [comment]
> Please try the code below. If it works, please tell me, thanks!
> 
> ```js
> function getCookie(name) {
>   const value = `; ${document.cookie}`;
>   const parts = value.split(`; ${name}=`);
>   if (parts.length === 2) return parts.pop().split(';').shift();
> }
> let token = 'Error';
> if (document.cookie.includes('ltoken=')) {
>   token = `ltoken=${getCookie('ltoken')}; ltuid=${getCookie('ltuid')};`;
> } else if (document.cookie.includes('ltoken_v2=')) {
>   token = `account_mid_v2=${getCookie('account_mid_v2')}; account_id_v2=${getCookie('account_id_v2')}; ltoken_v2=${getCookie('ltoken_v2')}; ltmid_v2=${getCookie('ltmid_v2')}; ltuid_v2=${getCookie('ltuid_v2')};`;
> } else { 
>   token = document.cookie;
> }
> let ask = confirm(token + '\n\nPress enter, then paste the token into your Google Apps Script Project');
> if (ask) {
>   copy(token);
>   msg = token;
> } else {
>   msg = 'Cancel';
> }
> ```

Well, I think I got the v2 token (although it's long as hell) but it's reamain the same
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/145992865/8bd471a4-c6f0-496f-823c-64e8aad1dd09)
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/145992865/261d5e57-5488-41cd-8a4b-0df11950d12a)
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/145992865/0a5bdb86-e8a0-4336-ad6e-2262ebfc90c3)

**Comment by canaria3406** [comment]
Hoyolab reset the cookie as HTTPOnly cookie, so it's not possible to directly access or read HTTPOnly cookies using the browser's developer console or JavaScript code.  
getToken.js will never work again. :(

**Comment by vomenh1804** [comment]
So how do I get the cookies manually?

> Hoyolab reset the cookie as HTTPOnly cookie, so it's not possible to directly access or read HTTPOnly cookies using the browser's developer console or JavaScript code. getToken.js will never work again. :(

**Comment by vomenh1804** [comment]
Nevermind, I've found a way to manually get the token:
- Go to [HoYoLAB](https://www.hoyolab.com/) (https://www.hoyolab.com/) and log in.
- Go to your profile page.
- Open the developer tools (F12 or Ctrl+Shift+I).
- Go to the "Network" tab.
- Click on the "Preserve Log" / "Persist Logs" button.
- Refresh the page.
- Click on the getGameRecordCard request where the method is "GET" (it should be named "getGameRecordCard" with your HoYoLab UID).
- Go to the "Cookies" tab.
- Copy the "ltoken" or "ltoken_v2" cookie value.
- Copy the "ltuid" or "ltuid_v2" cookie value.
Cre: https://github.com/Joshua-Noakes1/mei-cards
