### ISSUE TITLE
Since canaria didn't response to my PR, please use my version, which have a huge improvements.

### ISSUE THREAD

**Issue by NatsumeAoii** [canaria3406/hoyolab-auto-sign#37]
as you can see on my title, i do a huge improvements based on canaria logic, also i adding the experimental code which have a discord and a telegram notification. i still need a further help from u guys to improve its overall capabilities.

**Comment by SkyfireX** [comment]
Anyidea what it means if it says "not logged in" in telegram?

does that mean my token has an error?

**Comment by NatsumeAoii** [comment]
yes, ur cookies was got changed, or its false cookie, read my readme.md how and what cookies that u need

**Comment by NatsumeAoii** [comment]
Btw, Just use my newer code, there have more detalied error or some issue when somthing happens.
