### ISSUE TITLE
Cant find ituid_v2 cookie value

### ISSUE THREAD

**Issue by hooman10109** [canaria3406/hoyolab-auto-sign#40]
Simply cant find the value 
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/73069885/39a1edb8-b185-49e4-a852-67bf36057f98)

**Comment by canaria3406** [comment]
Just use the `ltoken` and `ltuid`.

**Comment by hooman10109** [comment]
I get user is not logged in error though, is there anything that can be done?

**Comment by hooman10109** [comment]
Or are there other cookies I need to get in order to use this code
