### ISSUE TITLE
Tears of Themis

### ISSUE THREAD

**Issue by Queenhardt** [canaria3406/hoyolab-auto-sign#46]
IDK, if this is the right place, but if ZZZ is going to be added why not add every Hoyo game? It seems like ToT is the only one missing then.
I saw an old pull request about that and added it to my code but it doesn't seem to work (https://github.com/canaria3406/hoyolab-auto-sign/pull/13), my Discord message always says "Too many attempts. Try again later", while every other says "OK" or smth like "You've already checked in today, Trailblazer~/Traveler~/Captain~/Proxy~". 
Is it possible to add this game too, or is there maybe a problem with why it doesn't work?

**Comment by Xiaoqianghepipi** [comment]
maybe need problem is send too many attempts,it need a wait time to login to get price

**Comment by Xiaoqianghepipi** [comment]
but I don't know how to write latency time in Google Apps Script,if it has wait time,it can work

**Comment by Xiaoqianghepipi** [comment]
To fix the issue temporarily,you can create more projects and perform check-in tasks separately (up to two games per task),the projects need run in different times

**Comment by canaria3406** [comment]
Merge pull request #45
