### ISSUE TITLE
README.md 請補充說明

### ISSUE THREAD

**Issue by ingrid-z** [canaria3406/hoyolab-auto-sign#6]
README.md 請補充說明
1. myTelegramID 如何取得。
2. 如何創建一個自己的bot，以及如何產生token。
我做了一下功課。執行成功但是不知為何bot收不到通知。
不知道哪裡錯了，可否協助？感謝。
![image](https://github.com/canaria3406/hoyolab-auto-sign/assets/22465481/83eb1122-b964-4392-8f40-84dd8021b563)

myTelegramID 是指自身帳號ID還是bot ID？
我試了上述兩個，bot都收不到任何通知。

另比對中英script程式碼行數不符，英文版有缺漏61-73行的程式碼。

_Originally posted by @ingrid-z in https://github.com/canaria3406/hoyolab-auto-sign/issues/1#issuecomment-1545710131_

**Comment by canaria3406** [comment]
2. **myTelegramID** - 請填入您的 Telegram ID.

   向 [@IDBot](https://t.me/myidbot) 傳送 `/getid` 指令以取得您的 Telegram ID，複製ID並填入"括號內"即可。

直接向這個BOT輸入 `/getid` 指令就能拿到你的Telegram ID了。
你的 Telegram ID 是你自身帳號的ID，會長得像 `1XXXXXXX0`，不會是網頁連結。

你的telegramBotToken應該沒問題。

另外英文版少的程式碼是將通知翻譯成中文用的，英文使用者用不到。

**Comment by ingrid-z** [comment]
works as intended.
感謝協助。
